CREATE DATABASE IF NOT EXISTS `teste` ;

USE `teste`;

CREATE TABLE `teste` (
	`id` INT(10) NOT NULL AUTO_INCREMENT,
	`Codigo` INT(10) NULL DEFAULT NULL,
	`User` VARCHAR(50) NULL DEFAULT NULL,
	`Host` VARCHAR(50) NULL DEFAULT NULL,
	`db` VARCHAR(50) NULL DEFAULT NULL,
	`Command` VARCHAR(50) NULL DEFAULT NULL,
	`Time` VARCHAR(50) NULL DEFAULT NULL,
	`State` VARCHAR(50) NULL DEFAULT NULL,
	`Info` VARCHAR(50) NULL DEFAULT NULL,
	`ddmmaaaa` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
ROW_FORMAT=DYNAMIC
AUTO_INCREMENT=1;